custom:
  prop: hello world
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics
service-b:
  ribbon:
    eureka:
      enabled: true
      ServerListRefreshInterval: 1000
